on:
  push:
    branches:
      - main
    paths:
      - events/README.md
      - events/index.html

jobs:
  dockerize:
    runs-on: ubuntu-latest
    environment:
      name: Events
      url:  https://asf-event-data.s3.us-west-2.amazonaws.com/README.md

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy README and Index to S3
        run: |
          aws s3 cp ./events/README.md s3://asf-event-data/README.md
          aws s3 cp ./events/index.html s3://asf-event-data/index.html
